### ISSUE TITLE
Sever security issue

### ISSUE THREAD

**Issue by NuriYuri** [realAfonso/web-gts-online-panel#1]
Hi, by reading api.php I just saw that you're using PHP string interpolation for your queries. 

And from what I see, none of the variable are escaped, I think we should use https://www.php.net/manual/en/mysqli.real-escape-string.php to ensure all values are properly escaped and we don't have issue if some hater of a specific fangame does something like :

`api?i=0;DELETE FROM gts where game=id`

**Comment by omanoloneto** [comment]
Thanks for the warning, I fixed this with a slightly different solution than the one you proposed, but that has the same function.

**Comment by NuriYuri** [comment]
Great :D  
As lons as it's fixed it's fine :3
